TRAIN:
  BATCH_SIZE : 60
  MAX_EPOCH : 100
  SEED : 6
  LR : 2e-4
  WEIGHT_DECAY : 1e-4
  MASK_PROBABILITY : 0.15
  TARGET_RANDOM_DROP_RATIO : 0.7
  MUTAION: 0.2
  C_PATH : "C_1280_2000_8.pkl"
  PR_PATH : "pr_f_1280_2000.pkl"
  DICT_SIZE : 8
  MLM : True
  SAVE_MODEL : True
  SAVE_LAST_EPOCH : True
  OUTPUT_DIR : "seed_"

  # Bias diagnosis during evaluation
  BIAS_DIAG : False
  OVERRIDE_MODE : "zero"  # [zero, mean]
  USE_DEBIASED_SCORE : False
  LAMBDA_T : 1.0
  LAMBDA_D : 1.0
 # BIAS_DIAG_STAGE : "test"  # [val, test, both]  在train阶段让模型学习debias，test阶段才进行偏差诊断 有说服力
 # Bias diagnosis during evaluation
  

#debias gonfigs
  LAMBDA_T_GRID : [0.2, 0.4, 0.6, 0.8, 1.0]
  LAMBDA_D_GRID : [0.2, 0.4, 0.6, 0.8, 1.0]
  DEBIAS_OVERRIDE_MODE : "zero"  # [zero, mean] for reporting grid-search debias result