TRAIN:
  BATCH_SIZE : 10
  MAX_EPOCH : 1
  SEED : 6
  LR : 2e-4
  WEIGHT_DECAY : 1e-4
  MASK_PROBABILITY : 0.15
  TARGET_RANDOM_DROP_RATIO : 0.7
  MUTAION: 0 # 氨基酸随机替换概率，1: 氨基酸随机删除概率，2: 氨基酸随机插入概率  默认关闭该功能
  ENABLE_AA_RANDOMIZATION : False #新增参数：是否启用aa字典随机化 默认关闭
  C_PATH : "C_1280_2000_8.pkl"
  PR_PATH : "pr_f_1280_2000.pkl"
  DICT_SIZE : 3
  MLM : True
  SAVE_MODEL : True
  SAVE_LAST_EPOCH : True
  OUTPUT_DIR : "seed_"


  LAMBDA_DRUG : 0.5
  LAMBDA_PROTEIN : 0.5
  CF_MODE_DRUG : "mean"
  CF_MODE_PROTEIN : "mean"
  ENABLE_LAMBDA_GRID_SEARCH : True
  LAMBDA_DRUG_GRID : [0.0, 0.25, 0.5, 0.75, 1.0]
  LAMBDA_PROTEIN_GRID : [0.0, 0.25, 0.5, 0.75, 1.0]
