TRAIN:
  BATCH_SIZE : 60
  MAX_EPOCH : 100
  SEED : 6
  LR : 2e-4
  WEIGHT_DECAY : 1e-4
  MASK_PROBABILITY : 0.15
  TARGET_RANDOM_DROP_RATIO : 0.7
  MUTAION: 0.2
  C_PATH : "C_1280_2000_8.pkl"
  PR_PATH : "pr_f_1280_2000.pkl"
  DICT_SIZE : 8
  MLM : True
  SAVE_MODEL : True
  SAVE_LAST_EPOCH : True
  OUTPUT_DIR : "seed_"
  USE_CONFOUNDER : True
  FORWARD_MODE : "tapb"
  ENABLE_PROTEIN_AUGMENTATION : True
